# Generated by Django 2.2.3 on 2019-07-26 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IMGSched', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='meet_type',
            field=models.CharField(choices=[('General', 'General'), ('Private', 'Private')], default='General', max_length=10),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
